name: Build and Deploy
on:
    push:
        branches:
            - main
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
            	uses: actions/checkout@v2

            - name: Install and Build
            	uses: borales/actions-yarn@v2.3.0
				with:
					cmd: install
				uses: borales/actions-yarn@v2.3.0
				with:
					cmd: build

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@v4.2.2
              with:
                  branch: gh-pages
                  folder: dist
